# Generated by Django 3.2.9 on 2021-11-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='equipment_category',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
