# Generated by Django 3.2.9 on 2021-11-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_remove_approvals_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='case_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
