# Generated by Django 3.2.9 on 2021-11-20 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_mlalgorithm_mlalgorithmstatus_mlrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
        ),
        migrations.DeleteModel(
            name='MLRequest',
        ),
        migrations.DeleteModel(
            name='MLAlgorithm',
        ),
        migrations.DeleteModel(
            name='MLAlgorithmStatus',
        ),
    ]
